version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: start SPAs
          command: yarn w:examples
          background: true
      - run: sleep 30
      - run: yarn e2e
  deploy:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
        name: install crowdin
        command:
        - sudo apt-get update
        - sudo apt-get install default-jre rsync
        - wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
        - sudo dpkg -i crowdin.deb
      - run: yarn build
      - run: cd examples && gh-pages -d build

workflows:
  version: 2
  e2e:
    triggers:
      - schedule:
          cron: "0 5 * * *" # UTC time
          filters:
            branches:
              only:
                - master
    jobs:
      - test
  build-test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
